# Site settings
permalink: pretty
title: BlazeCSS - Open Source Modular CSS Framework
description: Blaze is designed to give you structure and a good starting point for your website.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blazecss.com" # the base hostname & protocol for your site
twitter_username: blazecss
version: '1.1.4'

# Build settings
markdown: kramdown

# Navigation
navigation-getting-started:
- text: Install
  url: /getting-started/install/

- text: Custom build
  url: /getting-started/custombuild/


navigation-community:
- text: Contributing
  url: /community/contributing/


navigation-components:
- text: Addresses
  url: /components/addresses/

- text: Alerts
  url: /components/alerts/

- text: Badges
  url: /components/badges/

- text: Bubbles
  url: /components/bubbles/

- text: Buttons
  url: /components/buttons/

- text: Calendars
  url: /components/calendars/

- text: Cards
  url: /components/cards/

- text: Containers
  url: /components/containers/

- text: Drawers
  url: /components/drawers/

- text: Grid
  url: /components/grid/

- text: Headings
  url: /components/headings/

- text: Images
  url: /components/images/

- text: Inputs
  url: /components/inputs/

- text: Lists
  url: /components/lists/

- text: Menus
  url: /components/menus/

- text: Modals
  url: /components/modals/

- text: Overlays
  url: /components/overlays/

- text: Pagination
  url: /components/pagination/

- text: Ranges
  url: /components/ranges/

- text: Tables
  url: /components/tables/

- text: Typography
  url: /components/typography/

- text: Tabs
  url: /components/tabs/

- text: Tags
  url: /components/tags/

- text: Toggles
  url: /components/toggles/

- text: Toasts
  url: /components/toasts/

- text: Base
  url: /components/base/
